[package]
name = "dfwad"
version = "0.1.0"
edition = "2021"
rust-version = "1.77"

[dependencies]
byteorder = "1.5.0"
clap = {version = "4.5.41", features = ["derive", "cargo"]}
encoding_rs = "0.8.35"
flate2 = "1.1.2"
walkdir = "2.5.0"
